baseURL = "https://zxp-77hub.github.io/"
languageCode = "zh-cn"
theme = "book"
title = "菜鸟集市"
author = "张学鹏"
publishdir = "docs"

[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark]
        [markup.goldmark.extensions]
            definitionList = true
            footnote = true
            linkify = true
            strikethrough = true
            table = true
            taskList = true
            typographer = false
        [markup.goldmark.renderer]
            hardWraps = false
            unsafe = true
            xHTML = false
    [markup.highlight]
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 6
        ordered = false